# Generated by Django 4.1.7 on 2023-02-16 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Відгук')),
                ('chat_id', models.CharField(blank=True, max_length=9, verbose_name='ID в чаті')),
                ('processed', models.BooleanField(default=False, verbose_name='Опрацьовано')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Видалено')),
            ],
            options={
                'verbose_name': 'Відгук',
                'verbose_name_plural': 'Відгуки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name_driver', models.CharField(max_length=255, verbose_name='Водій')),
                ('event', models.CharField(max_length=20, verbose_name='Подія')),
                ('chat_id', models.CharField(blank=True, max_length=9, verbose_name='Індетифікатор чата')),
                ('status_event', models.BooleanField(default=False, verbose_name='Працює')),
                ('created_at', models.DateTimeField(editable=False, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Подія',
                'verbose_name_plural': 'Події',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.user')),
                ('role', models.CharField(choices=[('CLIENT', 'Client'), ('PARTNER', 'Partner'), ('DRIVER', 'Driver'), ('DRIVER_MANAGER', 'Driver manager'), ('SERVICE_STATION_MANAGER', 'Service station manager'), ('SUPPORT_MANAGER', 'Support manager'), ('OWNER', 'Owner')], default='OWNER', max_length=50)),
            ],
            options={
                'verbose_name': 'Власник',
                'verbose_name_plural': 'Власники',
            },
            bases=('app.user',),
        ),
        migrations.CreateModel(
            name='Report_of_driver_debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.CharField(max_length=255, verbose_name='Водій')),
                ('image', models.ImageField(upload_to='.', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Видалено')),
            ],
            options={
                'verbose_name': 'Звіт заборгованості водія',
                'verbose_name_plural': 'Звіти заборгованості водіїв',
                'ordering': ['driver'],
            },
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клієнт', 'verbose_name_plural': 'Клієнти'},
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name': 'Водій', 'verbose_name_plural': 'Водії'},
        ),
        migrations.AlterModelOptions(
            name='drivermanager',
            options={'verbose_name': 'Менеджер водія', 'verbose_name_plural': 'Менеджер водіїв'},
        ),
        migrations.AlterModelOptions(
            name='driverratelevels',
            options={'verbose_name': 'Рівень рейтингу водія', 'verbose_name_plural': 'Рівень рейтингу водіїв'},
        ),
        migrations.AlterModelOptions(
            name='fleet',
            options={'verbose_name': 'Автопарк', 'verbose_name_plural': 'Автопарки'},
        ),
        migrations.AlterModelOptions(
            name='repairreport',
            options={'verbose_name': 'Звіт про ремонт', 'verbose_name_plural': 'Звіти про ремонти'},
        ),
        migrations.AlterModelOptions(
            name='servicestation',
            options={'verbose_name': 'Сервісний Центр', 'verbose_name_plural': 'Сервісні центри'},
        ),
        migrations.AlterModelOptions(
            name='servicestationmanager',
            options={'verbose_name': 'Менеджер сервісного центра', 'verbose_name_plural': 'Менеджери сервісних центрів'},
        ),
        migrations.AlterModelOptions(
            name='supportmanager',
            options={'verbose_name': 'Менеджер служби підтримки', 'verbose_name_plural': 'Менеджери служби підтримки'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Користувач', 'verbose_name_plural': 'Користувачі'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': 'Автомобіль', 'verbose_name_plural': 'Автомобілі'},
        ),
        migrations.AddField(
            model_name='fleets_drivers_vehicles_rate',
            name='pay_cash',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fleets_drivers_vehicles_rate',
            name='withdraw_money',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('PARTNER', 'Partner'), ('DRIVER', 'Driver'), ('DRIVER_MANAGER', 'Driver manager'), ('SERVICE_STATION_MANAGER', 'Service station manager'), ('SUPPORT_MANAGER', 'Support manager'), ('OWNER', 'Owner')], default='CLIENT', max_length=50),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_status',
            field=models.CharField(default='Offline', max_length=35, verbose_name='Статус водія'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('PARTNER', 'Partner'), ('DRIVER', 'Driver'), ('DRIVER_MANAGER', 'Driver manager'), ('SERVICE_STATION_MANAGER', 'Service station manager'), ('SUPPORT_MANAGER', 'Support manager'), ('OWNER', 'Owner')], default='DRIVER', max_length=50),
        ),
        migrations.AlterField(
            model_name='drivermanager',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('PARTNER', 'Partner'), ('DRIVER', 'Driver'), ('DRIVER_MANAGER', 'Driver manager'), ('SERVICE_STATION_MANAGER', 'Service station manager'), ('SUPPORT_MANAGER', 'Support manager'), ('OWNER', 'Owner')], default='DRIVER_MANAGER', max_length=50),
        ),
        migrations.AlterField(
            model_name='driverratelevels',
            name='fleet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fleet', verbose_name='Автопарк'),
        ),
        migrations.AlterField(
            model_name='repairreport',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.driver', verbose_name='Водій'),
        ),
        migrations.AlterField(
            model_name='repairreport',
            name='end_of_repair',
            field=models.DateTimeField(blank=True, verbose_name='Закінчення ремонту'),
        ),
        migrations.AlterField(
            model_name='repairreport',
            name='numberplate',
            field=models.CharField(max_length=12, unique=True, verbose_name='Номер автомобіля'),
        ),
        migrations.AlterField(
            model_name='repairreport',
            name='repair',
            field=models.CharField(max_length=255, verbose_name='Фото звіту про ремонт'),
        ),
        migrations.AlterField(
            model_name='repairreport',
            name='start_of_repair',
            field=models.DateTimeField(blank=True, verbose_name='Початок ремонту'),
        ),
        migrations.AlterField(
            model_name='repairreport',
            name='status_of_payment_repair',
            field=models.BooleanField(default=False, verbose_name='Статус оплати'),
        ),
        migrations.AlterField(
            model_name='servicestation',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='servicestation',
            name='lat',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='servicestation',
            name='lat_zone',
            field=models.CharField(max_length=1, verbose_name='Пояс-Широти'),
        ),
        migrations.AlterField(
            model_name='servicestation',
            name='lon',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Довгота'),
        ),
        migrations.AlterField(
            model_name='servicestation',
            name='lon_zone',
            field=models.CharField(max_length=1, verbose_name='Пояс-Довготи'),
        ),
        migrations.AlterField(
            model_name='servicestation',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='servicestation',
            name='owner',
            field=models.CharField(max_length=150, verbose_name='Власник'),
        ),
        migrations.AlterField(
            model_name='servicestationmanager',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('PARTNER', 'Partner'), ('DRIVER', 'Driver'), ('DRIVER_MANAGER', 'Driver manager'), ('SERVICE_STATION_MANAGER', 'Service station manager'), ('SUPPORT_MANAGER', 'Support manager'), ('OWNER', 'Owner')], default='SERVICE_STATION_MANAGER', max_length=50),
        ),
        migrations.AlterField(
            model_name='servicestationmanager',
            name='service_station',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='app.servicestation', verbose_name='Сервісний центр'),
        ),
        migrations.AlterField(
            model_name='supportmanager',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('PARTNER', 'Partner'), ('DRIVER', 'Driver'), ('DRIVER_MANAGER', 'Driver manager'), ('SERVICE_STATION_MANAGER', 'Service station manager'), ('SUPPORT_MANAGER', 'Support manager'), ('OWNER', 'Owner')], default='SUPPORT_MANAGER', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='chat_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Індетифікатор чата'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Видалено'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Електрона пошта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='user',
            name='second_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Прізвище'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='car_status',
            field=models.CharField(default='Serviceable', max_length=18, verbose_name='Статус автомобіля'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Видалено'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='app.driver', verbose_name='Водій'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='licence_plate',
            field=models.CharField(max_length=24, unique=True, verbose_name='Номерний знак'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(max_length=50, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(max_length=20, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_address', models.CharField(max_length=255)),
                ('latitude', models.CharField(max_length=10)),
                ('longitude', models.CharField(max_length=10)),
                ('to_the_address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=13)),
                ('chat_id_client', models.CharField(max_length=15)),
                ('sum', models.CharField(max_length=30)),
                ('payment_method', models.CharField(max_length=70)),
                ('status_order', models.CharField(max_length=70)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='app.driver')),
            ],
        ),
    ]
