# Generated by Django 4.1.7 on 2023-03-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_comment_event_owner_report_of_driver_debt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='driver_manager_id',
        ),
        migrations.AlterField(
            model_name='drivermanager',
            name='driver_id',
            field=models.ManyToManyField(blank=True, null=True, to='app.driver', verbose_name='Driver'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(default='Електро', max_length=20, verbose_name='Тип'),
        ),
    ]
