# Generated by Django 4.1.7 on 2023-03-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_driver_driver_manager_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=255, verbose_name='Прізвище')),
                ('email', models.EmailField(max_length=255, verbose_name='Електронна пошта')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Телефон')),
                ('role', models.CharField(max_length=255, verbose_name='Роль')),
                ('status_job_application', models.BooleanField(default=False, verbose_name='Опрацьована')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачі заявки')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
