# Generated by Django 4.1.7 on 2023-03-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_jobapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribeUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Електрона пошта')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Створено')),
            ],
            options={
                'verbose_name': 'Підписник',
                'verbose_name_plural': 'Підписники',
            },
        ),
        migrations.AddField(
            model_name='driver',
            name='driver_manager_id',
            field=models.ManyToManyField(blank=True, to='app.drivermanager'),
        ),
    ]
